baseURL = 'https://mannustack.dev/'
languageCode = 'en-us'
title = 'Your Blog Title'
theme = 'PaperMod'

[pagination]
pagerSize = 10

[params]
env = "production"
title = "Mannu's Stack"
description = "Your blog description"
author = "Mannu Silva"
defaultTheme = "auto"  # auto, light or dark
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

[params.homeInfoParams]
Title = "Mannu's Stack"
Content = "Your blog introduction text here"

[[params.socialIcons]]
name = "github"
url = "https://github.com/emsilva"

#[[params.socialIcons]]
#name = "twitter"
#url = "https://twitter.com/emsilva"

[menu]
[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 30
